services:
  db:
    image: "postgres"
    volumes: 
      - tikilord-data:/var/lib/postgresql/data
    secrets:
      - db_name
      - db_user
      - db_pass
    environment:
      - POSTGRES_DB_FILE=/run/secrets/db_name
      - POSTGRES_USER_FILE=/run/secrets/db_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_pass
    networks:
      - tiki-net
  django:
    image: "tikilord:latest"
    tty: true
    ports:
      - "9000:9000"
    secrets:
      - db_name
      - db_user
      - db_pass
    environment:
      - TIKILORD_DB_NAME=/run/secrets/db_name
      - TIKILORD_DB_USER=/run/secrets/db_user
      - TIKILORD_DB_PASS=/run/secrets/db_pass
    networks:
      - tiki-net
    depends_on:
      - db
volumes:
  tikilord-data:
networks:
  tiki-net:
secrets:
  db_name:
    file: ./secrets/db_name
  db_user:
    file: ./secrets/db_user
  db_pass:
    file: ./secrets/db_pass
