# Generated by Django 4.1.2 on 2022-10-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_position_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
